---
find_company_website:
  description: 'Using the provided company name: {company_name}, utilize the WebsiteSearchTool
    to search for the company''s official website. Formulate a search query like ''{company_name}
    official website'' to improve accuracy.'
  expected_output: The official website URL for {company_name}.
  async_execution: false
  agent: website_finder
extract_company_description:
  description: Once the official website URL for {company_name} is retrieved, use
    the ScrapeElementFromWebsiteTool to navigate to the website and extract the company
    description. This might involve targeting an 'About' section or similar HTML element
    that succinctly describes the company.
  expected_output: A detailed textual description of the company {company_name} as
    retrieved from its website.
  async_execution: false
  agent: description_scraper
  context:
  - find_company_website
